//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PhoneDBDataModel", "FK_Phone_PhoneCD", "PhoneCD", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(phone.dal.PhoneCD), "Phone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(phone.dal.Phone), true)]

#endregion

namespace phone.dal
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PhoneDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PhoneDBEntities object using the connection string found in the 'PhoneDBEntities' section of the application configuration file.
        /// </summary>
        public PhoneDBEntities() : base("name=PhoneDBEntities", "PhoneDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PhoneDBEntities object.
        /// </summary>
        public PhoneDBEntities(string connectionString) : base(connectionString, "PhoneDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PhoneDBEntities object.
        /// </summary>
        public PhoneDBEntities(EntityConnection connection) : base(connection, "PhoneDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Phone> Phones
        {
            get
            {
                if ((_Phones == null))
                {
                    _Phones = base.CreateObjectSet<Phone>("Phones");
                }
                return _Phones;
            }
        }
        private ObjectSet<Phone> _Phones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhoneCD> PhoneCDs
        {
            get
            {
                if ((_PhoneCDs == null))
                {
                    _PhoneCDs = base.CreateObjectSet<PhoneCD>("PhoneCDs");
                }
                return _PhoneCDs;
            }
        }
        private ObjectSet<PhoneCD> _PhoneCDs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Phones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhones(Phone phone)
        {
            base.AddObject("Phones", phone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhoneCDs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhoneCDs(PhoneCD phoneCD)
        {
            base.AddObject("PhoneCDs", phoneCD);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PhoneDBDataModel", Name="Phone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Phone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Phone object.
        /// </summary>
        /// <param name="pHONE_ID">Initial value of the PHONE_ID property.</param>
        /// <param name="pHONE_CD">Initial value of the PHONE_CD property.</param>
        /// <param name="pHONE_TX">Initial value of the PHONE_TX property.</param>
        /// <param name="cREATE_DT">Initial value of the CREATE_DT property.</param>
        /// <param name="mOD_DT">Initial value of the MOD_DT property.</param>
        /// <param name="aPPLICANT_ID">Initial value of the APPLICANT_ID property.</param>
        public static Phone CreatePhone(global::System.Decimal pHONE_ID, global::System.String pHONE_CD, global::System.Decimal pHONE_TX, global::System.DateTime cREATE_DT, global::System.DateTime mOD_DT, global::System.Decimal aPPLICANT_ID)
        {
            Phone phone = new Phone();
            phone.PHONE_ID = pHONE_ID;
            phone.PHONE_CD = pHONE_CD;
            phone.PHONE_TX = pHONE_TX;
            phone.CREATE_DT = cREATE_DT;
            phone.MOD_DT = mOD_DT;
            phone.APPLICANT_ID = aPPLICANT_ID;
            return phone;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PHONE_ID
        {
            get
            {
                return _PHONE_ID;
            }
            set
            {
                if (_PHONE_ID != value)
                {
                    OnPHONE_IDChanging(value);
                    ReportPropertyChanging("PHONE_ID");
                    _PHONE_ID = StructuralObject.SetValidValue(value, "PHONE_ID");
                    ReportPropertyChanged("PHONE_ID");
                    OnPHONE_IDChanged();
                }
            }
        }
        private global::System.Decimal _PHONE_ID;
        partial void OnPHONE_IDChanging(global::System.Decimal value);
        partial void OnPHONE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PHONE_CD
        {
            get
            {
                return _PHONE_CD;
            }
            set
            {
                OnPHONE_CDChanging(value);
                ReportPropertyChanging("PHONE_CD");
                _PHONE_CD = StructuralObject.SetValidValue(value, false, "PHONE_CD");
                ReportPropertyChanged("PHONE_CD");
                OnPHONE_CDChanged();
            }
        }
        private global::System.String _PHONE_CD;
        partial void OnPHONE_CDChanging(global::System.String value);
        partial void OnPHONE_CDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PHONE_TX
        {
            get
            {
                return _PHONE_TX;
            }
            set
            {
                OnPHONE_TXChanging(value);
                ReportPropertyChanging("PHONE_TX");
                _PHONE_TX = StructuralObject.SetValidValue(value, "PHONE_TX");
                ReportPropertyChanged("PHONE_TX");
                OnPHONE_TXChanged();
            }
        }
        private global::System.Decimal _PHONE_TX;
        partial void OnPHONE_TXChanging(global::System.Decimal value);
        partial void OnPHONE_TXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CREATE_DT
        {
            get
            {
                return _CREATE_DT;
            }
            set
            {
                OnCREATE_DTChanging(value);
                ReportPropertyChanging("CREATE_DT");
                _CREATE_DT = StructuralObject.SetValidValue(value, "CREATE_DT");
                ReportPropertyChanged("CREATE_DT");
                OnCREATE_DTChanged();
            }
        }
        private global::System.DateTime _CREATE_DT;
        partial void OnCREATE_DTChanging(global::System.DateTime value);
        partial void OnCREATE_DTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MOD_DT
        {
            get
            {
                return _MOD_DT;
            }
            set
            {
                OnMOD_DTChanging(value);
                ReportPropertyChanging("MOD_DT");
                _MOD_DT = StructuralObject.SetValidValue(value, "MOD_DT");
                ReportPropertyChanged("MOD_DT");
                OnMOD_DTChanged();
            }
        }
        private global::System.DateTime _MOD_DT;
        partial void OnMOD_DTChanging(global::System.DateTime value);
        partial void OnMOD_DTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal APPLICANT_ID
        {
            get
            {
                return _APPLICANT_ID;
            }
            set
            {
                OnAPPLICANT_IDChanging(value);
                ReportPropertyChanging("APPLICANT_ID");
                _APPLICANT_ID = StructuralObject.SetValidValue(value, "APPLICANT_ID");
                ReportPropertyChanged("APPLICANT_ID");
                OnAPPLICANT_IDChanged();
            }
        }
        private global::System.Decimal _APPLICANT_ID;
        partial void OnAPPLICANT_IDChanging(global::System.Decimal value);
        partial void OnAPPLICANT_IDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PhoneDBDataModel", "FK_Phone_PhoneCD", "PhoneCD")]
        public PhoneCD PhoneCD
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneCD>("PhoneDBDataModel.FK_Phone_PhoneCD", "PhoneCD").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneCD>("PhoneDBDataModel.FK_Phone_PhoneCD", "PhoneCD").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PhoneCD> PhoneCDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneCD>("PhoneDBDataModel.FK_Phone_PhoneCD", "PhoneCD");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PhoneCD>("PhoneDBDataModel.FK_Phone_PhoneCD", "PhoneCD", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PhoneDBDataModel", Name="PhoneCD")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhoneCD : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhoneCD object.
        /// </summary>
        /// <param name="pHONE_CD">Initial value of the PHONE_CD property.</param>
        /// <param name="pHONE_TX">Initial value of the PHONE_TX property.</param>
        /// <param name="mOD_DT">Initial value of the MOD_DT property.</param>
        public static PhoneCD CreatePhoneCD(global::System.String pHONE_CD, global::System.String pHONE_TX, global::System.DateTime mOD_DT)
        {
            PhoneCD phoneCD = new PhoneCD();
            phoneCD.PHONE_CD = pHONE_CD;
            phoneCD.PHONE_TX = pHONE_TX;
            phoneCD.MOD_DT = mOD_DT;
            return phoneCD;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PHONE_CD
        {
            get
            {
                return _PHONE_CD;
            }
            set
            {
                if (_PHONE_CD != value)
                {
                    OnPHONE_CDChanging(value);
                    ReportPropertyChanging("PHONE_CD");
                    _PHONE_CD = StructuralObject.SetValidValue(value, false, "PHONE_CD");
                    ReportPropertyChanged("PHONE_CD");
                    OnPHONE_CDChanged();
                }
            }
        }
        private global::System.String _PHONE_CD;
        partial void OnPHONE_CDChanging(global::System.String value);
        partial void OnPHONE_CDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PHONE_TX
        {
            get
            {
                return _PHONE_TX;
            }
            set
            {
                OnPHONE_TXChanging(value);
                ReportPropertyChanging("PHONE_TX");
                _PHONE_TX = StructuralObject.SetValidValue(value, false, "PHONE_TX");
                ReportPropertyChanged("PHONE_TX");
                OnPHONE_TXChanged();
            }
        }
        private global::System.String _PHONE_TX;
        partial void OnPHONE_TXChanging(global::System.String value);
        partial void OnPHONE_TXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MOD_DT
        {
            get
            {
                return _MOD_DT;
            }
            set
            {
                OnMOD_DTChanging(value);
                ReportPropertyChanging("MOD_DT");
                _MOD_DT = StructuralObject.SetValidValue(value, "MOD_DT");
                ReportPropertyChanged("MOD_DT");
                OnMOD_DTChanged();
            }
        }
        private global::System.DateTime _MOD_DT;
        partial void OnMOD_DTChanging(global::System.DateTime value);
        partial void OnMOD_DTChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PhoneDBDataModel", "FK_Phone_PhoneCD", "Phone")]
        public EntityCollection<Phone> Phones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Phone>("PhoneDBDataModel.FK_Phone_PhoneCD", "Phone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Phone>("PhoneDBDataModel.FK_Phone_PhoneCD", "Phone", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
